name: Sync

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror GitHub to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/WenSimEHRP
          dst: gitee/wensimehrp
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "OpenTTD-bucket"
